 What is a Python library? Why do we use Python libraries?

In [ ]:
'''
A collection of pre-written code modules that provide functionalities to accomplish certain tasks. 
These libraries contain functions, classes, and methods that can be imported into Python 
script or program, allowing us to use them to perform various operations without having to write 
the code from scratch.

1. Libraries provide pre-written code that can be reused across multiple projects, 
    saving time and effort in writing code from scratch.
2. Many Python libraries are designed to handle specific tasks or domains, such as data analysis, 
    machine learning, web development, scientific computing, etc
3.  Python libraries are often developed and maintained by a community of contributors, 
    providing ongoing support, updates, and bug fixes.
'''

What is the d0ifference between Numpy array and List?

In [ ]:
'''
NumPy arrays and Python lists are both used to store collections of data, but there are several differences between them:

Homogeneity:
- NumPy arrays are homogeneous, meaning all elements must have the same data type. 
    This allows for more efficient storage and operations.
- Python lists can contain elements of different data types, making them heterogeneous.

Memory Efficiency:
-NumPy arrays are more memory efficient compared to Python lists, especially for large datasets, 
    because they store data in a contiguous block of memory.
-Python lists are less memory efficient because they store references to objects, which are scattered across memory.

Performance:
-NumPy arrays offer better performance for numerical operations and computations compared to Python lists, 
    especially for operations involving large datasets. This is because NumPy arrays are implemented in C and optimized for performance.
-Python lists are slower for numerical computations because they are interpreted in Python and involve more overhead.

Functionality:
- NumPy arrays provide a wide range of mathematical functions and operations optimized for 
    numerical computing, such as matrix operations, linear algebra, statistical functions, and random number generation.
- Python lists offer more general-purpose functionality and are suitable for a wide range of tasks beyond numerical computing.

Syntax:
- NumPy arrays support vectorized operations, allowing you to perform operations on entire arrays at once without using loops.
- Python lists require explicit iteration using loops to perform operations on individual elements.
'''

Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

shape = arr.shape

size = arr.size

dimension = arr.ndim

# Print the results
print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)


Shape: (3, 4)
Size: 12
Dimension: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = arr[0]
print("First Row:", first_row)


First Row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
element = arr[2, 3]  

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [18]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]
print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [20]:
import numpy as np

random_matrix = np.random.rand(3, 3)
print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.19825009 0.78173109 0.1274816 ]
 [0.4415636  0.35356467 0.63358369]
 [0.57330404 0.59194798 0.51179029]]


8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
'''
- `np.random.rand` generates random numbers from a uniform distribution over the interval [0, 1), 
    whereas `np.random.randn` generates random numbers from a standard normal distribution.

- `np.random.rand` requires shape parameters to define the size of the output array, 
    while `np.random.randn` can take either individual dimensions or a tuple representing the shape.

- `np.random.rand` is suitable when you need random numbers uniformly distributed between 0 and 1, 
    while `np.random.randn` is useful for generating random numbers following a standard normal distribution.
'''

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#new_arr = arr[:, :, np.newaxis]
new_arr = np.expand_dims(arr, axis=2)

print("Original array:")
print(arr)
print("\nArray with increased dimension:")
print(new_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_arr = np.transpose(arr)
print("Original array:")
print(arr)
print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [13]:
import numpy as np

A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # Assuming you want to perform matrix multiplication and transpose B2

# 3. Add both the matrices
matrix_addition = A2 + B2

# 4. Subtract matrix B from A
matrix_subtraction = A2 - B2

# 5. Divide Matrix B by A
matrix_division = np.divide(B2, A2)

# Print the results
print("1. Index wise multiplication:")
print(index_wise_multiplication)
print("\n2. Matrix multiplication:")
print(matrix_multiplication)
print("\n3. Matrix addition:")
print(matrix_addition)
print("\n4. Matrix subtraction:")
print(matrix_subtraction)
print("\n5. Matrix division:")
print(matrix_division)


1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix division:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
numpy.ndarray.byteswap()

13. What is the significance of the p.linalg.inv function?

In [ ]:
'''
The significance of the numpy.linalg.inv function is that it computes the multiplicative inverse of a matrix. 
In linear algebra, the multiplicative inverse (or matrix inverse) of a square matrix A is another matrix A^-1, 
such that the product of A and A^-1 equals the identity matrix. This function is particularly useful in solving 
systems of linear equations and in various matrix operations.
'''

14. What does the p.reshape function do, and how is it used?

In [17]:
''' 
The numpy.reshape function is used to change the shape of an array without changing its data. 
It returns a new array with the specified shape. The function takes the new shape as input and 
rearranges the elements of the input array to fit the new shape. If the total number of elements 
in the new shape is not equal to the total number of elements in the original array, a ValueError is raised. 
Here's an example of how it's used:'''
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])


reshaped_arr = np.reshape(arr, (3, 2))

print("Original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)

Original array:
[[1 2 3]
 [4 5 6]]

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


15. What is broadcasting in Numpy?

In [ ]:
'''
Broadcasting in NumPy is a powerful mechanism that allows arithmetic operations to be 
performed between arrays of different shapes, without explicitly reshaping the arrays. 

When performing operations involving arrays with different shapes, NumPy automatically 
broadcasts the arrays to make their shapes compatible. Broadcasting involves two steps:

a. Alignment: The dimensions of the arrays are aligned to make them compatible for 
element-wise operations. If the arrays have different numbers of dimensions, 
the smaller array is padded with ones on its left side.

b. Element-wise operation: After alignment, the operation is performed element-wise on the broadcasted arrays.

Broadcasting simplifies the syntax and improves the efficiency of array operations in NumPy, allowing for concise and efficient code.
'''